### ISSUE TITLE
Request to add some guidelines

### ISSUE THREAD

**Issue by Jassi10000-zz** [TibebeJS/emoji-captcha-bot#3]
@TibebeJS  Sir can you please put in readme that what does this project does , how it will work or how to get started with it,  it will really help me as am interested to know about this project of yours

**Comment by TibebeJS** [comment]
Hey there @Jassi10000 , thanks for your comment! I am sorry for the very late response.
I've added some documentation for the time being as per your request. I have been busy with work and stuff and didn't really had time to finish up the project but I'm back to it now.
Also, contributions are very welcomed. Feel free to contribute.
Thanks :)
